# Generated by Django 6.0.1 on 2026-02-01 11:22

import bulletin.models
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulletin", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulletinpost",
            name="school",
        ),
        migrations.AlterModelOptions(
            name="bulletinpost",
            options={"ordering": ["-publish_at", "-created_at"]},
        ),
        migrations.RenameField(
            model_name="bulletinpost",
            old_name="event_end",
            new_name="submission_deadline",
        ),
        migrations.RenameField(
            model_name="bulletinpost",
            old_name="rejection_reason",
            new_name="summary",
        ),
        migrations.RemoveField(
            model_name="bulletinpost",
            name="event_start",
        ),
        migrations.RemoveField(
            model_name="bulletinpost",
            name="job_deadline",
        ),
        migrations.AddField(
            model_name="bulletinpost",
            name="contact_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name="bulletinpost",
            name="contact_phone",
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name="bulletinpost",
            name="organization_name",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name="bulletinpost",
            name="publish_at",
            field=models.DateTimeField(
                db_index=True, default=django.utils.timezone.now
            ),
        ),
        migrations.AddField(
            model_name="bulletinpost",
            name="reference_no",
            field=models.CharField(blank=True, max_length=80),
        ),
        migrations.AddField(
            model_name="bulletinpost",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="attachment_pdf",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="bulletins/",
                validators=[bulletin.models.validate_pdf],
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="body",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletin_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="expires_at",
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="location",
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("EVENT", "Event"),
                    ("JOB", "Job"),
                    ("NOTICE", "Notice"),
                    ("TENDER", "Tender / Procurement"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="status",
            field=models.CharField(
                choices=[
                    ("OPEN", "Open"),
                    ("CLOSED", "Closed"),
                    ("AWARDED", "Awarded"),
                    ("DRAFT", "Draft"),
                ],
                db_index=True,
                default="OPEN",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="title",
            field=models.CharField(max_length=180),
        ),
        migrations.DeleteModel(
            name="School",
        ),
    ]
