# Generated by Django 6.0.1 on 2026-02-01 15:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bulletin", "0002_remove_bulletinpost_school_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bulletinpost",
            name="created_by",
        ),
        migrations.AddField(
            model_name="bulletinpost",
            name="author",
            field=models.ForeignKey(
                blank=True,
                help_text="User who created this bulletin post.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="bulletin_posts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="location",
            field=models.CharField(
                blank=True, help_text="e.g. 'Lusaka'", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="organization_name",
            field=models.CharField(
                blank=True, help_text="e.g. 'Pemba High School'", max_length=120
            ),
        ),
        migrations.AlterField(
            model_name="bulletinpost",
            name="reference_no",
            field=models.CharField(
                blank=True, help_text="e.g. 'KSS/PROC/01/2026'", max_length=80
            ),
        ),
        migrations.AddIndex(
            model_name="bulletinpost",
            index=models.Index(
                fields=["post_type", "status"], name="bulletin_bu_post_ty_081924_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="bulletinpost",
            index=models.Index(
                fields=["-publish_at"], name="bulletin_bu_publish_7d3b92_idx"
            ),
        ),
    ]
