# Generated by Django 6.0.1 on 2026-01-27 13:31

import content.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpost',
            name='pdf_file',
            field=models.FileField(upload_to=content.models.pdf_upload_path, validators=[content.models.validate_pdf_file]),
        ),
    ]
