# Generated by Django 6.0.1 on 2026-06-23 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_documentpost_description_documentpost_exam_year_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documentpost',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
